{{ if .Values.sonarr.enabled }}
---
### CONFIGMAP
## INIT-CONTAINER
apiVersion: v1
data:
  config.xml: |
    <Config>
      <UrlBase>{{ .Values.sonarr.ingress.path }}</UrlBase>
    </Config>
  init-sonarr.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ ! -f /sonarr-config/config.xml ]; then
      cp -n /init-sonarr/config.xml /sonarr-config/config.xml
      echo "### No configuration found, intialized with default settings ###"
    fi
kind: ConfigMap
metadata:
  name: init-sonarr-cm
---
## Secrets
apiVersion: v1
kind: Secret
metadata:
  name: "sonarr-api-secret"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "sonarr-api-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $secret to existing secret data or generate a random one when not exists
  {{- $secret := (get $secretData "sonarr-api-secret") | default (randAlphaNum 32 | b64enc) }}
  sonarr-api-secret: {{ $secret | quote }}
---
## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: sonarr
      annotations:
        k8s.grafana.com/scrape: "true"
        k8s.grafana.com/metrics-portNumber: "9707"
        k8s.grafana.com/job: "sonarr-exporter"
    spec:
      initContainers:
        - name: config-sonarr
          image: docker.io/ubuntu:groovy
          command: ["/init-sonarr/init-sonarr.sh"]
          volumeMounts:
            - mountPath: /init-sonarr
              name: init-files-sonarr
          {{- if .Values.sonarr.volume }}
            - name: {{ .Values.sonarr.volume.name }}
              mountPath: /sonarr-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /sonarr-config
              subPath: "{{ .Values.general.storage.subPaths.config }}/sonarr"
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: sonarr-config
          image: "{{ .Values.sonarr.container.image }}:{{ .Values.sonarr.container.tag | default .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: "{{ .Values.sonarr.ingress.path }}/ping"
              port: {{ .Values.sonarr.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 20
          env:
            - name: ApiKey
              valueFrom:
                secretKeyRef:
                  name: sonarr-api-secret
                  key: sonarr-api-secret
          ports:
            - name: sonarr-port
              containerPort: {{ .Values.sonarr.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.sonarr.volume }}
            - name: {{ .Values.sonarr.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/sonarr"
          {{- end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}"
            - name: mediaserver-volume
              mountPath: "/tv"
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
            - name: mediaserver-volume
              mountPath: "/data/completed/tv"
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
          {{- with .Values.sonarr.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: exportarr
          image: ghcr.io/onedr0p/exportarr:latest
          imagePullPolicy: Always
          args:
            - sonarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://sonarr.default.svc.cluster.local:8989"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: sonarr-api-secret
                  key: sonarr-api-secret
          ports:
            - name: monitoring
              containerPort: 9707
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.sonarr.volume }}
        - name: {{ .Values.sonarr.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.sonarr.volume.name }}
        {{- end }}
        - name: init-files-sonarr
          configMap:
            defaultMode: 493
            name: init-sonarr-cm
      {{- with merge .Values.sonarr.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sonarr.service.type }}
  ports:
    - port: {{ .Values.sonarr.service.port }}
      targetPort: {{ .Values.sonarr.container.port }}
      protocol: TCP
{{ if eq .Values.sonarr.service.type "NodePort" }}
      nodePort: {{ .Values.sonarr.service.nodePort }}
{{ end }}
      name: sonarr-port
  selector:
    app: sonarr
---
{{ if .Values.sonarr.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: sonarr-lb
  {{- with .Values.sonarr.service.extraLBAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.sonarr.service.port }}
      targetPort: {{ .Values.sonarr.container.port }}
      protocol: TCP
      name: sonarr-port
  selector:
    app: sonarr
{{ end }}
---
### INGRESS
{{ if .Values.sonarr.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.sonarr.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.sonarr.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.sonarr.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.sonarr.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: {{ .Values.sonarr.service.port }}
{{ if .Values.general.ingress.enableSubdomains }}
    - host: {{ printf "%s.%s" "sonarr" .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: {{ .Values.sonarr.service.port }}
{{ end }}
{{ end }}
{{ end }}
