{{- if .Values.transmission.enabled -}}
### CONFIGMAP
## INIT-CONTAINER
apiVersion: v1
data:
  init-transmission.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ ! -f /transmission-config/settings.json ]; then
      cp -n /init-transmission/settings.json /transmission-config/settings.json
      echo "### No configuration found, intialized with default settings ###"
    fi
  settings.json: |
    {
        "alt-speed-down": 50,
        "alt-speed-enabled": false,
        "alt-speed-time-begin": 540,
        "alt-speed-time-day": 127,
        "alt-speed-time-enabled": false,
        "alt-speed-time-end": 1020,
        "alt-speed-up": 50,
        "bind-address-ipv4": "0.0.0.0",
        "bind-address-ipv6": "::",
        "blocklist-enabled": false,
        "blocklist-url": "http://www.example.com/blocklist",
        "cache-size-mb": 4,
        "dht-enabled": true,
        "download-dir": "/{{ .Values.general.storage.subPaths.downloads }}",
        "download-queue-enabled": true,
        "download-queue-size": 5,
        "encryption": 1,
        "idle-seeding-limit": 30,
        "idle-seeding-limit-enabled": false,
        "incomplete-dir": "/{{ .Values.general.storage.subPaths.downloads }}/incomplete",
        "incomplete-dir-enabled": true,
        "lpd-enabled": false,
        "message-level": 2,
        "peer-congestion-algorithm": "",
        "peer-id-ttl-hours": 6,
        "peer-limit-global": 200,
        "peer-limit-per-torrent": 50,
        "peer-port": {{ .Values.transmission.service.peer.port }},
        "peer-port-random-high": 65535,
        "peer-port-random-low": 49152,
        "peer-port-random-on-start": false,
        "peer-socket-tos": "default",
        "pex-enabled": true,
        "port-forwarding-enabled": true,
        "preallocation": 1,
        "prefetch-enabled": true,
        "queue-stalled-enabled": true,
        "queue-stalled-minutes": 30,
        "ratio-limit": 2,
        "ratio-limit-enabled": false,
        "rename-partial-files": true,
        "rpc-authentication-required": {{ .Values.transmission.config.auth.enabled }},
        "rpc-bind-address": "0.0.0.0",
        "rpc-enabled": true,
        "rpc-host-whitelist": "",
        "rpc-host-whitelist-enabled": false,
        "rpc-password": {{ .Values.transmission.config.auth.password | quote }} ,
        "rpc-port": 9091,
        "rpc-url": "{{ .Values.transmission.ingress.path }}/",
        "rpc-username": {{ .Values.transmission.config.auth.username | quote }},
        "rpc-whitelist": "127.0.0.1",
        "rpc-whitelist-enabled": false,
        "scrape-paused-torrents-enabled": true,
        "script-torrent-done-enabled": false,
        "script-torrent-done-filename": "",
        "seed-queue-enabled": false,
        "seed-queue-size": 10,
        "speed-limit-down": 100,
        "speed-limit-down-enabled": false,
        "speed-limit-up": 100,
        "speed-limit-up-enabled": false,
        "start-added-torrents": true,
        "trash-original-torrent-files": false,
        "umask": 2,
        "upload-slots-per-torrent": 14,
        "utp-enabled": false,
        "watch-dir": "/watch",
        "watch-dir-enabled": true
    }
kind: ConfigMap
metadata:
  name: init-transmission-cm
---
## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: transmission
      annotations:
        k8s.grafana.com/scrape: "true"
        k8s.grafana.com/metrics-portNumber: "29091"
        k8s.grafana.com/job: "transmission-exporter"
    spec:
      initContainers:
        - name: config-transmission
          image: docker.io/ubuntu:groovy
          command: ["/init-transmission/init-transmission.sh"]
          volumeMounts:
            - mountPath: /init-transmission
              name: init-files-transmission
          {{ if .Values.transmission.volume }}
            - name: {{ .Values.transmission.volume.name }}
              mountPath: /transmission-config
          {{ else }}
            - name: mediaserver-volume
              mountPath: "/transmission-config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/transmission"
          {{ end }}
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      # securityContext:
      #   capabilities:
      #     add: ["NET_ADMIN"]
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: transmission-config
          image: "{{ .Values.transmission.container.image }}:{{ .Values.transmission.container.tag | default .Values.general.image_tag }}"
          imagePullPolicy: Always
          # readinessProbe:
          #   httpGet:
          #     path: "{{ .Values.transmission.ingress.path }}/"
          #     port: {{ .Values.transmission.container.port.utp }}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 20
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          #   # must enable ipv6 to have njal.la work
          #   - net.ipv6.conf.all.disable_ipv6=0
          env:
            # https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
            - name: TZ
              value: "Europe/London"
            - name: OPENVPN_PROVIDER
              value: "{{ .Values.transmission.vpn.provider }}"
            - name: VPN_TYPE
              value: "{{ .Values.transmission.vpn.type }}"
            - name: OPENVPN_USERNAME
              value: {{ .Values.transmission.vpn.user | quote }}
            - name: OPENVPN_PASSWORD
              value: {{ .Values.transmission.vpn.city }}
            - name: LOCAL_NETWORK
              value: "10.1.216.0/24"
          volumeMounts:
          {{ if .Values.transmission.volume }}
            - name: {{ .Values.transmission.volume.name }}
              mountPath: /config
          {{ else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/transmission"
          {{ end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}"
            - name: mediaserver-volume
              mountPath: "/data/incomplete"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}/incomplete"
            - name: mediaserver-volume
              mountPath: "/data/completed/movies"
              subPath: "{{ .Values.general.storage.subPaths.movies }}"
            - name: mediaserver-volume
              mountPath: "/data/completed/tv"
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
          {{- with .Values.transmission.resources }}
            # - name: tunnel
            #   mountPath: /dev/net/tun
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: transmission-exporter
          image: sandrotosi/simple_transmission_exporter
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 29091
              protocol: TCP
          env:
            - name: TRANSMISSION_HOST
              value: "localhost"
            - name: TRANSMISSION_PORT
              value: "9091"
            - name: TRANSMISSION_USERNAME
              value: "admin"
            - name: TRANSMISSION_PASSWORD
              value: "admin"
      volumes:
        {{ if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{ else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{ end }}
        {{ if .Values.transmission.volume }}
        - name: {{ .Values.transmission.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.volume.name }}
        {{ end }}
        - name: tunnel
          hostPath:
            path: /dev/net/tun
            type: ""
        - name: init-files-transmission
          configMap:
            defaultMode: 493
            name: init-transmission-cm
      {{- with merge .Values.transmission.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.transmission.service.utp.type }}
  ports:
    - port: {{ .Values.transmission.service.utp.port }}
      targetPort: {{ .Values.transmission.container.port.utp }}
      protocol: TCP
      name: http
{{ if eq .Values.transmission.service.utp.type "NodePort" }}
      nodePort: {{ .Values.transmission.service.utp.nodePort }}
{{ end }}
  selector:
    app: transmission
---
### INGRESS
{{ if .Values.transmission.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.transmission.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.transmission.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.transmission.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.transmission.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: {{ .Values.transmission.service.utp.port }}
{{ if .Values.general.ingress.enableSubdomains }}
    - host: {{ printf "%s.%s" "transmission" .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: {{ .Values.transmission.service.utp.port }}
{{ end }}
{{ end }}
{{ end }}
